language: ruby

notifications:
  email: false

rvm:
  - 2.0
  - 2.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem install fakeweb

script:
  - "bundle exec rake spec"
